site_name: AeroFusion: Autonomous BLIMP Navigation and Sensor Integration Platform
site_url: https://RAS598-2025-S-Team03.github.io
repo_url: https://github.com/RAS598-2025-S-Team03/RAS598-2025-S-Team03.github.io
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: custom_theme/
  palette:
    primary: blue
    accent: indigo
  font:
    text: Roboto
  logo: static/logo.svg
  favicon: static/logo.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow    
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - content.action.edit
    - navigation.footer
#    - navigation.sections
#    - navigation.expand
#    - navigation.instant # doesn't work that well

nav:
  - Home: index.md
  - Gantt Chart: gantt.md  # Added Gantt chart page

markdown_extensions:
  - attr_list #add attributes using curly brackets to images, see https://squidfunk.github.io/mkdocs-material/reference/images/
  - md_in_html # see https://squidfunk.github.io/mkdocs-material/reference/images/
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde: {}
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

draft_docs: |
  **/*_unpublished.md
  **/*_draft.md
  **/*_draft**
  
plugins:
  - search
  - glightbox # allow resize images, see https://squidfunk.github.io/mkdocs-material/reference/images/

extra_css:
  - stylesheets/extra.css  

extra_javascript:
 - javascripts/mathjax.js
 - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
not_in_nav: |
  static
  
copyright: "Copyright &copy; 2024 RAS598: Team 3"

extra:
  generator: false
  social:
    - icon: fontawesome/regular/file-code
      link: /2023_fall
      name: 2023 Site    
